name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # daily update
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          user: roonakyadav
          template: classic

          base: header, activity, community, repositories, metadata

          plugin_activity: yes
          plugin_activity_limit: 12
          plugin_activity_days: 365
          plugin_activity_filter: all

          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 365

          plugin_lines: yes

          plugin_followup: yes
